module.exports = {
    SUCCESS: {code:200, msg:"操作成功"},
    NEED_LOGIN: {code:401, msg:"身份无效，请登录后操作"},
    BAN: {code:402, msg:'账号被封禁'},
    NO_OPERATOR_AUTH: {code:403, msg:"无权限操作"},
    SYSTEM_ERROR: {code:500, msg:"系统错误"},
    USERNAME_EXIST: {code:501, msg:"用户名已存在"},
    PHONENUMBER_EXIST: {code:502, msg:"手机号已存在"},
    EMAIL_EXIST: {code:503, msg:"邮箱已存在"},
    REQUIRE_USERNAME: {code:504, msg:"必需填写用户名"},
    LOGIN_ERROR: {code:505, msg:"用户名或密码错误"},
    CONTENT_NOT_NULL: {code:506, msg:"评论内容不能为空"},
    DONT_DO_THIS_TWICE: {code:507, msg:"请不要重复操作"},
    USER_NOT_EXIST: {code:508, msg:"用户不存在"},
    CANT_DO_THIS_FOR_YOURSELF: {code:509, msg:"不能对自己进行此操作"},
    GROUP_NOT_EXIST: {code:510, msg:"群组不存在"},
    OBJECT_ALREADY_IN_GROUP: {code:511, msg:"该对象已成为群组成员"},
    ALREADY_BEEN_Friend: {code:512, msg:"已成为好友关系"},
    ALREADY_BEEN_OWNER: {code:512, msg:"您已是该群组的所有者"},
    ALREADY_BEEN_MEMBER: {code:513, msg:"您已是该群组的成员"},
    NOT_GROUP_MEMBER: {code:514, msg:"您不是该群组的成员"},
    TRANSFER_GROUP_TO_OTHERS: {code: 515, msg:"请先转让群组给其他成员"},
    FILETYPE_NOT_ALLOW: {code:516, msg:"文件类型不受支持"},
    NOT_MODIFIED: {code:517, msg:"未修改"},
    NOT_DELETED: {code:518, msg:"未删除"},
    COMPLETE_PARTIAL: {code:519, msg:"完成部分操作"},
    PARAM_INVALID: {code: 999, msg:"参数非法"}
}